# Write a program to store seven fruits in a list entered by the user.
fruits= []
f1= input(int("enter fruit name: "))
fruits.append(f1)
f2= input(int("enter fruit name: "))
fruits.append(f2)
f3= input(int("enter fruit name: "))
fruits.append(f3)
f4= input(int("enter fruit name: "))
fruits.append(f4)
f5= input(int("enter fruit name: "))
fruits.append(f5)
f6= input(int("enter fruit name: "))
fruits.append(f6)
f7= input(int("enter fruit name: "))
fruits.append(f7)
print(fruits)